# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/XML-LibXML-Augment/project>
	:test-requirement    [ :on "Test::More 0.61"^^:CpanId ];
	:runtime-requirement [ :on "Perl 5.008"^^:CpanId ];
	:runtime-requirement [ :on "Class::Inspector"^^:CpanId ];
	:runtime-requirement [ :on "Module::Runtime"^^:CpanId ];
	:runtime-requirement [ :on "XML::LibXML 1.95"^^:CpanId ];
	:runtime-requirement [ :on "match::simple"^^:CpanId ].

